### PR TITLE
Adds a SetMap service message to support swap maps functionality in amcl

### PR DESCRIPTION
**Pull request by liz-murphy**
This supports the addition of a new service to amcl which allows the map to be changed and an initial pose set in one action. https://github.com/ros-planning/navigation/pull/301

### CODE REVIEW

**Comment by tfoote** [comment]
This looks reasonable to me. Could you email ros-sig-navigation for feedback/review.

**Comment by mikeferguson** [comment]
Just a note @tfoote -- this came out of my suggestion on the original navigation PR.

+1 from me

**Comment by mikeferguson** [comment]
Also, not sure what the needs of @liz-murphy are, but this might something desiring a backport to indigo-devel (since it is LTS and I think most robot manufactures are probably sticking to LTS releases).

**Comment by liz-murphy** [comment]
Thanks - yes, we'd be after a backport if possible. I'll send that email to ros-sig-navigation.

**Comment by mikeferguson** [comment]
@tfoote discussion on ros-sig-nav was positive -- nobody raised any real issues -- can we get a merge?

**Comment by tfoote** [comment]
Thread in ros-sig-navigation: https://groups.google.com/forum/#!topic/ros-sig-navigation/RdHvIIYF4i4

**Comment by stwirth** [comment]
@tfoote how can we get a backport to indigo for this? Should we open a new PR?

**Comment by tfoote** [comment]
Since it's a pure addition we can backport it. If you could open a pull-request that would be greatly appreciated.

**Comment by stwirth** [comment]
Backport PR here: https://github.com/ros/common_msgs/pull/56

**Pull request merged**
