### PR TITLE
Adds a SetMap service message to support swap maps functionality in amcl

### PR DESCRIPTION
**Pull request by stwirth**
This is a backport of 04cceab to indigo.

@liz-murphy @mikeferguson @tfoote I just noticed that the `initial_pose` should rather be a `PoseWithCovarianceStamped` to support passing the covariance, analogue to amcl's topic `/initial_pose`. What do you think? The idea behind this new service was to get the same as publishing a new map and a new initial pose but with the feedback from the handler of those messages to make sure they actually arrived and are in use.

### CODE REVIEW

**Comment by tfoote** [comment]
It makes sense to me to have covariance like the `/initial_pose` topic.

**Comment by liz-murphy** [comment]
Yes I agree. Forcing it to have a default covariance was a bit shortsighted.

**Comment by mikeferguson** [comment]
Concur as well @stwirth please also open a PR to update Jade

**Comment by stwirth** [comment]
Changed `initial_pose` to be `PoseWithCovarianceStamped`.

**Comment by stwirth** [comment]
Same for jade: https://github.com/ros/common_msgs/pull/57

**Comment by tfoote** [comment]
Thanks.

**Pull request merged**
