### PR TITLE
added action definition for getting maps from map_server

### PR DESCRIPTION
**Pull request by jonbinney**
Adds an action that does the same thing as the static_map service call, for people who want to use actionlib instead of services.

### CODE REVIEW

**Comment by hershwg** [comment]
This pull request looks good to me, but I'm not merging it right off the bat because of the recent email from @tfoote saying "Please hold on new merges for groovy so we can get a sync to public."

This is an addition of new a new .action file, so I don't expect it to cause any regressions.

**Comment by dirk-thomas** [comment]
Why should the same operation which already exists as a service be available as an action if it does not have any progress message? That looks like duplicating API to me.

**Comment by hershwg** [comment]
We have some infrastructure which doesn't support service calls or latched topics, so an action call seemed like a simple way to get the behavior we want through the supported pub/sub communications.

We are also under the impression that service calls are being discouraged in favor of topic-based solutions like actionlib.

**Comment by dirk-thomas** [comment]
I assumed that service are always available when actionlib is. If that is not the case sure it makes sense to also expose the functionality as an action.

**Comment by hershwg** [comment]
So... can I merge it?  Or would you like to?  Or do we need to wait for something else to happen?

**Comment by dirk-thomas** [comment]
That should be the maintainers responsibility: @tfoote 
I was just asking questions out of curiosity.

**Comment by tfoote** [comment]
@hershwg FYI the merge limitation is just for pulls into rosdistro not for individual packages.

**Pull request merged**
