### PR TITLE
adding a JointCommands message (complement of JointState.msg)

### PR DESCRIPTION
**Pull request by hsu**
Proposal for setting joint commands.  Feedback welcome.

### CODE REVIEW

**Comment by chadrockey** [comment]
I don't think that commands belong in sensor_msgs.  Especially since this message has a lot of overlap with the discussion here: https://github.com/ros/common_msgs/pull/10

Should likely be with control_msgs or controller_msgs depending on which one survived - assuming this doesn't have significant redundancy with one of those messages.

**Comment by chadrockey** [comment]
http://ros.org/wiki/control_msgs was the survivor.

**Comment by isucan** [comment]
I really do not think this should go in sensor_msgs. I think this can go to control_msgs though, if there is no overlap with other messages.

**Comment by hsu** [comment]
agreed, control_msgs is a better place for this.

**Pull request closed without merging**
