### PR TITLE
add MultiDOFJointTrajectory

### PR DESCRIPTION
**Pull request by isucan**
migrate multi-dof trajectory messages from MoveIt

### CODE REVIEW

**Comment by davetcoleman** [comment]
Questions:
- If you are moving these two messages from [moveit_msgs](https://github.com/ros-planning/moveit_msgs/tree/groovy-devel/msg) why are you not also including `MultiDOFJointState.msg` for consistency?
- Why are trajectory messages in `common_msgs` but `control_msgs` in [ros_controls/control_msgs](https://github.com/ros-controls/control_msgs/tree/master/control_msgs)?
- This is planned to be in Hydro? You'll remove that message from the hydro-devel branch of `moveit_msgs`?

Other than that, it looks fine to me.

**Comment by isucan** [comment]
These are all good points. Here are my thoughts: I am not sure about the structure of the state message yet, and I do not think it belongs to trajectory_msgs. I would like to have these messages in hydro, yes, and the remove the corresponding ones from moveit_msgs. 
Wrt your ros_control comment, I think that is a separate issue. I am not sure about this yet. Are trajectory messages always and only used for control?

**Comment by davetcoleman** [comment]
There's certainly a lot of overlap - I'd vote on consolidating these type messages in the `ros_controls` organization.

For example, there are two JointTrajectory.action in `ros_controls`
- [controller_msgs](https://github.com/ros-controls/ros_controllers/blob/master/controllers_msgs/action/JointTrajectory.action)
- [control_msgs](https://github.com/ros-controls/control_msgs/blob/master/control_msgs/action/JointTrajectory.action)

Maybe put all 3 of these messages (control, controller, trajectory) in the same organization and try to reduce duplicates. Also duplicates in moveit_msgs (as you are doing now, yay!)

**Comment by chadrockey** [comment]
+1 looks fine to me as long as they are removed from moveit_msgs in Hydro.  I assume MoveITs review process settled on the content of the messages, so I have nothing to add.

@davetcoleman JointState is technically a sensor message, so MultiDOFJointState should be in sensor_msgs, not trajectory_msgs when it is ready.

**Comment by sachinchitta** [comment]
(1) controller_msgs and control_msgs - one of these needs to disappear fast and its probably controller_msgs - I will open a separate ticket for this
(2) Since JointState is already in sensor_msgs, MultiDOFJointState should also go there.
(3) The Multi-dof trajectory message is going to have overlap with the CartesianTrajectory message suggested elsewhere - if we are moving things into common_msgs, we should ideally converge on one message but I think that might be hard right now given that the messages are used for slightly different things (although MultiDOF is a subset of Cartesian the way it is defined now). One option is to adopt CartesianTrajectory and just use its kinematic parts when doing kinematic planning.

**Comment by isucan** [comment]
@sachinchitta can you point to the CartesianTrajectory message you are talking about? It seems semantically different though, so even if it has the same content, I think we should have both here.

I am thinking of the following steps for Hydro:
- merge this message as is or with CartesianTrajectory additions, remove it from moveit_msgs
- move the trajectory_msgs package to the ros-control organization (I think we have Dave and myself proposing this so far; anyone against this?)
- move any relevant messages from controllers_msgs to control_msgs (not relevant for this merge, but I think it is very important to have this done for Hydro)
- add MultiDOFJointState to sensor_msgs

**Comment by davetcoleman** [comment]
I have removed controller_msgs here https://github.com/ros-controls/ros_controllers/pull/30

**Comment by sachinchitta** [comment]
In MultiDOFJointTrajectory, change to:

geometry_msgs/Transform[] transforms
geometry_msgs/Twist[] velocities
geometry_msgs/Twist[] accelerations 

In MultiDOFJointState change to:

geometry_msgs/Transform[] transforms
geometry_msgs/Twist[]  twist
geometry_msgs/Wrench[] wrench 

The assumption for both the twist and wrench is that they are specified in the frame of the header but the transform specifies the position of the reference point for both. The interpretation of the twist is also relative in this case - its the velocity of link B w.r.t link A (expressed in the reference frame specified in the header). 

Note that the use case for this message (so far) seems to be in dealing with planar or floating joints.

**Comment by isucan** [comment]
Is there anything else to be done before a merge can happen?

**Comment by tfoote** [comment]
Looks good.  I'll merge.

**Pull request merged**
