### PR TITLE
Update BatteryState.msg with temperatures

### LINKED ISSUE #139: Add cell_temperature to sensor_msgs/BatteryState
Often the temperatures are also measured but cannot be put in the BatteryState message.

### PR DESCRIPTION
**Pull request by reinzor**
Resolves https://github.com/ros/common_msgs/issues/139

### CODE REVIEW

**Comment by reinzor** [comment]
ping

**Comment by tfoote** [comment]
This looks like a reasonable addition. Changing a core message like this is not something that we can do during a release cycle so we will need to target Noetic. And it would be good to make sure to clearly document any migration requirements for existing users, both for requirements for their code base as well as bag migration rules for logged data.

**Review by clalancette — APPROVED** [review]
This looks good to me, provided that we create a new "noetic-devel" branch and target that.  We also want this in ROS 2; I'll make a separate PR for that.

**Comment by reinzor** [comment]
Can this be closed or do you still require this?

**Comment by clalancette** [comment]
I think this is a good idea to do; thanks for pinging.  Now that we are heading towards noetic, I'd create a new branch (noetic-devel), retarget this there, and then merge it.  @tfoote any thoughts?  If not, I'll just go ahead and do it.

**Comment by clalancette** [comment]
All right, I've created a new noetic-devel branch, then retargeted this PR at that branch.  I'm going to go ahead and merge it now.  We'll also need an update to https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml to update the branches there, which I'll do shortly.

**Comment by reinzor** [comment]
Thanks!

**Comment by tfoote** [comment]
Branch change upstream for cross reference. https://github.com/ros/rosdistro/pull/24094

**Comment by dirk-thomas** [comment]
This has not been released into Noetic. Doing so after the release breaks the interface.

**Comment by gavanderhoorn** [comment]
Just to keep things connected: this PR has come up on ROS Answers: [How to receive standard message that has changed format in noetic?](https://answers.ros.org/question/363757).

**Pull request merged**
